export const AUTH_FLOW_COOKIE_MAX_AGE_SECONDS = 15 * 60;

export const OTP_MAX_ATTEMPTS = 5;
export const OTP_MAX_RESENDS = 3;
export const OTP_EXPIRY_MINUTES = 10;
export const OTP_EXPIRY_SECONDS = OTP_EXPIRY_MINUTES * 60;
export const OTP_EXPIRY_MS = OTP_EXPIRY_SECONDS * 1000;
export const OTP_RESEND_COOLDOWN_MS = 30 * 1000;

export const VERIFICATION_SESSION_MAX_AGE_SECONDS = OTP_EXPIRY_SECONDS;

export const USER_SESSION_LIFETIME_SECONDS = 60 * 60 * 24;
export const USER_SESSION_REFRESH_THRESHOLD_SECONDS = 30 * 60;
export const USER_SESSION_ACTIVITY_WRITE_INTERVAL_SECONDS = 5 * 60;
export const USER_SESSION_HEARTBEAT_INTERVAL_MS = 5 * 60 * 1000;

export const USER_SESSION_COOKIE_BUFFER_SECONDS = 60 * 60 * 24 * 7;
export const DEVICE_ID_MAX_AGE_SECONDS = 60 * 60 * 24 * 365;
