export const reservedWorkspaceSlugs = [
  'app',
  'api',
  'create-workspace',
  'customer',
  'dashboard',
  'error-page',
  'host-transfer',
  'login',
  'payment',
  'platform',
  'post-login',
  'pricing',
  'select-workspace',
  'signup',
  'verify-otp',
  'verify-phone',
  'workspace-home',
] as const;
